### ISSUE TITLE
Missing publication details

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#23]
Compare:

http://alpha.lobid.org/resources/HT002732102
http://test.nwbib.de/HT013064214

**Comment by ChristophEwertowski** [comment]
Resources without shown publication details seem to be excluded from the faceting. If you search for "Energy" you get [34369 hits](http://alpha.lobid.org/resources/search?q=Energy) and for "Energy" and publication type "Periodical" there are [5472 hits](http://alpha.lobid.org/resources/search?q=Energy&t=Periodical) which weren't shown in the facets of the first search.

**Comment by fsteeg** [comment]
> Resources without shown publication details seem to be excluded from the faceting. If you search for "Energy" you get 34369 hits and for "Energy" and publication type "Periodical" there are 5472 hits which weren't shown in the facets of the first search.

I don't think this is related to the publication details, which are not show in general right now, for any resource.

As for the missing periodicals, we explicitly exclude these from the facet, see https://github.com/hbz/nwbib/issues/12#issuecomment-46407551 (which was for NWBib, but is the same here, or do we want different behavior here, @acka47?).

**Comment by acka47** [comment]
> As for the missing periodicals, we explicitly exclude these from the facet, see https://github.com/hbz/nwbib/issues/12#issuecomment-46407551 (which was for NWBib, but is the same here, or do we want different behavior here, @acka47?).

Obviously, we had the type `Periodical` in the data some time ago and then removed it because it was redundant with `Journal`. With https://github.com/hbz/lobid-resources/issues/121 we replaced `Journal` by `Periodical`. Thus, we now only have the type `Periodical` and should have it in the facet again. The question is how to label it. At https://de.wikipedia.org/wiki/Periodikum#Beispiele you find some examples for periodicals. I can't think of a common label to name it...

**Comment by ChristophEwertowski** [comment]
I also don't know a short, common name for it. There's a reason why I a loan word is used. A common term would be "regelmäßig erscheinendes Druckwerk | Druckschrift" but that's definitively too long for a facet. Also I don't get an idea of a fitting, small symbol.
