### ISSUE TITLE
Unify (aggregations) API for resources and organisations

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#26]
Currently, the organisations API delivers aggregations together with search results:

http://lobid.org/organisations/search?q=kunst&format=json

While the resources API has a separate route for aggregations, and omits them in the search:

http://alpha.lobid.org/resources/aggregations?q=kunst&format=json
http://alpha.lobid.org/resources/search?q=kunst&format=json

We should use a unified approach here. I think the separate route makes sense, as it avoids blowing up the search responses. Note that in the current resources search implementation however, we don't get the info about the number of hits, which is grouped with the aggregations in the organisations API. So I'd suggest the approach from organisations for `search`, but without the `aggregations` field in the first object of the result array, plus a sparate route for aggregations, as currently in resources.

What do you think, @acka47, @dr0i?

**Comment by dr0i** [comment]
+1 for your suggestion

**Comment by acka47** [comment]
Also +1 from me.

**Comment by acka47** [comment]
While doing this we should also take into account that http://sindice.com/vocab/search#totalResults doesn't resolve anymore (since 2015 actually, see http://lov.okfn.org/dataset/lov/vocabs/search). schema.org has a relevant class [`SearchResultPage`](https://schema.org/SearchResultsPage) but I can't find a property for number of results. However, I suggest replacing `http://sindice.com/vocab/search#totalResults` by `totalResults` only.

**Comment by acka47** [comment]
We could handle a search page as a `PagedCollection` with the [hydra vocabulary](http://www.hydra-cg.com/spec/latest/core/) and add information about: `previousPage`, `lastPage`, `nextPage` and `totalItems`. The OER World Map does this, see e.g. https://oerworldmap.org/resource.json?size=10

**Comment by fsteeg** [comment]
Since the implementation of this is distributed over two repos I think it makes more sense to have a single functional review here in this issue. For some background on the implementation see comments in https://github.com/hbz/lobid-resources/pull/238. Will assign the pull requests for code review.

Deployed to staging, see:

http://test.lobid.org/organisations/search?q=hbz&format=json
http://test.lobid.org/resources/search?q=nippes&format=json

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
+1

**Comment by acka47** [comment]
Just discussed offline with @fsteeg that we won't provide aggregations by default. The reason is that the fields aggregations are provided for are rather arbitrary (these currently are the fields we use for faceting). To do: Add an `aggregation` parameter that allows to configure for which fields aggregations are returned.

**Comment by fsteeg** [comment]
Reopen for customizable aggregations, see https://github.com/hbz/lobid-resources-web/issues/26#issuecomment-280296844.
